/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "JNUJun2019",
  "description": "路漫漫其修远兮，吾将上下而求索",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ],
    [
      "meta",
      {
        "name": "robots",
        "content": "all"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "HJG"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "hjg,前端,后台,vue,blog,vuepress-blog"
      }
    ]
  ],
  "pages": [
    {
      "title": "关于我",
      "frontmatter": {
        "title": "关于我",
        "date": "2020-06-14T22:38:39.000Z",
        "permalink": "/about",
        "isTimeLine": false,
        "sidebar": false,
        "isShowComment": true
      },
      "regularPath": "/views/about/",
      "relativePath": "views/about/README.md",
      "key": "v-42485c56",
      "path": "/about/",
      "headers": [
        {
          "level": 3,
          "title": "学习是没有止境的",
          "slug": "学习是没有止境的"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "bgImageStyle": {
          "height": "350px"
        },
        "isShowTitleInHome": true
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-1072a816",
      "path": "/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "title": "Vuepress基于Valine的评论功能",
      "frontmatter": {
        "title": "Vuepress基于Valine的评论功能",
        "date": "2020-12-20T20:06:12.000Z",
        "sidebarDepth": 2,
        "tags": [
          "Vuepress",
          "教程"
        ],
        "categories": [
          "前端front-end"
        ]
      },
      "regularPath": "/views/%E5%89%8D%E7%AB%AFfront-end/Vuepress%E5%9F%BA%E4%BA%8EValine%E7%9A%84%E8%AF%84%E8%AE%BA%E5%8A%9F%E8%83%BD.html",
      "relativePath": "views/前端front-end/Vuepress基于Valine的评论功能.md",
      "key": "v-219f4fa2",
      "path": "/views/%E5%89%8D%E7%AB%AFfront-end/Vuepress%E5%9F%BA%E4%BA%8EValine%E7%9A%84%E8%AF%84%E8%AE%BA%E5%8A%9F%E8%83%BD.html",
      "headers": [
        {
          "level": 2,
          "title": "安装插件",
          "slug": "安装插件"
        },
        {
          "level": 2,
          "title": "配置插件",
          "slug": "配置插件"
        },
        {
          "level": 3,
          "title": "vuepress项目引用",
          "slug": "vuepress项目引用"
        },
        {
          "level": 3,
          "title": "获取appId和appKey",
          "slug": "获取appid和appkey"
        },
        {
          "level": 3,
          "title": "更多配置项",
          "slug": "更多配置项"
        },
        {
          "level": 2,
          "title": "扩展功能",
          "slug": "扩展功能"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Vuepress Tags"
      },
      "regularPath": "/tag/Vuepress/",
      "key": "v-079695c8",
      "path": "/tag/Vuepress/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "教程 Tags"
      },
      "regularPath": "/tag/%E6%95%99%E7%A8%8B/",
      "key": "v-0e0479b5",
      "path": "/tag/教程/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "前端front-end Categories"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AFfront-end/",
      "key": "v-70f580b1",
      "path": "/categories/前端front-end/"
    }
  ],
  "themeConfig": {
    "type": "blog",
    "smoothScroll": true,
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "分类"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      }
    },
    "valineConfig": {
      "appId": "A9tLRTsEpIuTIVQapnEGWesu-gzGzoHsz",
      "appKey": "P4YaFoAHSpPHc6c9zdMu6zt1",
      "recordIP": true,
      "placeholder": "填写邮箱地址可以及时收到回复噢...",
      "visitor": true
    },
    "authorAvatar": "/avatar.png",
    "lastUpdated": "上次更新时间",
    "docsDir": "docs",
    "docsBranch": "source",
    "editLinks": true,
    "editLinkText": "在 GitHub 上编辑此页！",
    "author": "HJG",
    "startYear": "2020",
    "nav": [
      {
        "text": "主页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "时间轴",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "关于我",
        "link": "/about/",
        "icon": "reco-message"
      },
      {
        "text": "快速访问🎈",
        "icon": "reco-menu",
        "items": [
          {
            "text": "LeetCode",
            "link": "https://leetcode-cn.com/"
          },
          {
            "text": "Vue.js",
            "link": "https://cn.vuejs.org/v2/guide/"
          },
          {
            "text": "Can I Use",
            "link": "https://www.caniuse.com/#home"
          }
        ]
      }
    ],
    "search": true,
    "searchMaxSuggestions": 10,
    "sidebar": "auto",
    "friendLink": [
      {
        "title": "午后南杂",
        "desc": "Enjoy when you can, and endure when you must.",
        "email": "1156743527@qq.com",
        "link": "https://www.recoluan.com"
      },
      {
        "title": "vuepress-theme-reco",
        "desc": "A simple and beautiful vuepress Blog & Doc theme.",
        "logo": "https://vuepress-theme-reco.recoluan.com/icon_vuepress_reco.png",
        "link": "https://vuepress-theme-reco.recoluan.com"
      }
    ]
  }
}