/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "Vuepress": {
      "key": "Vuepress",
      "scope": "tags",
      "path": "/tag/Vuepress/",
      "pageKeys": [
        "v-219f4fa2"
      ]
    },
    "教程": {
      "key": "教程",
      "scope": "tags",
      "path": "/tag/教程/",
      "pageKeys": [
        "v-219f4fa2"
      ]
    }
  },
  "categories": {
    "前端front-end": {
      "key": "前端front-end",
      "scope": "categories",
      "path": "/categories/前端front-end/",
      "pageKeys": [
        "v-219f4fa2"
      ]
    }
  },
  "timeline": {}
}