/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "Vuepress",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/Vuepress/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "教程",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/教程/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "前端front-end",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/前端front-end/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
}]